# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

forceScheme <- function(p, dmat, max_it, tol, EPSILON, fraction) {
    .Call('mp_forceScheme', PACKAGE = 'mp', p, dmat, max_it, tol, EPSILON, fraction)
}

lamp <- function(X, sampleIndices, Ys) {
    .Call('mp_lamp', PACKAGE = 'mp', X, sampleIndices, Ys)
}

